/*
QUERY TO SELECT ALL WORDS WITH MORE OCCURRENCES

SELECT SUM(total_count) as total, value
FROM (

SELECT count(*) AS total_count, REPLACE(REPLACE(REPLACE(x.value,'?',''),'.',''),'!','') as value
FROM (
SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(t.quote, ' ', n.n), ' ', -1) value
  FROM quotes_en t CROSS JOIN 
(
   SELECT a.N + b.N * 10 + 1 n
     FROM 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
   ,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    ORDER BY n
) n
 WHERE n.n <= 1 + (LENGTH(t.quote) - LENGTH(REPLACE(t.quote, ' ', '')))
 ORDER BY value

) AS x
GROUP BY x.value

) AS y
GROUP BY value ORDER BY total DESC LIMIT 2;

*/

CREATE DATABASE quotes;
USE quotes;

# QUOTES TABLES
CREATE TABLE IF NOT EXISTS quotes_en(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote TEXT NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes_es(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote TEXT NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonimo',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes_pt(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote TEXT NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonimo',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  en_id int(11) DEFAULT NULL,
  es_id int(11) DEFAULT NULL,
  pt_id int(11) DEFAULT NULL,
  CONSTRAINT en_ibfk_1
    FOREIGN KEY (en_id) 
    REFERENCES quotes_en(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT es_ibfk_1 
    FOREIGN KEY (es_id) 
    REFERENCES quotes_es(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT pt_ibfk_1 
    FOREIGN KEY (pt_id) 
    REFERENCES quotes_pt(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# END OF QUOTES TABLES

# TOPICS
CREATE TABLE IF NOT EXISTS topics_en(
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(255) NOT NULL UNIQUE,
    seo_url varchar(255) NOT NULL,
  keywords varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topics_es( # Topics: Spanish
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(255) NOT NULL UNIQUE,
    seo_url varchar(255) NOT NULL,
  keywords varchar(2555) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topics_pt( # Topics: Portuguese
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(255) NOT NULL UNIQUE,
  seo_url varchar(255) NOT NULL,
  keywords varchar(255) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topics(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tEN_id int(11) DEFAULT NULL,
  tES_id int(11) DEFAULT NULL,
  tPT_id int(11) DEFAULT NULL,
  CONSTRAINT tEN_ibfk_1
    FOREIGN KEY (tEN_id) 
    REFERENCES topics_en(topicID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT tES_ibfk_1 
    FOREIGN KEY (tES_id) 
    REFERENCES topics_es(topicID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT tPT_ibfk_1 
    FOREIGN KEY (tPT_id) 
    REFERENCES topics_pt(topicID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topicsImages(
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tID int(11) DEFAULT NULL,
    img_url varchar(150) DEFAULT NULL,    
    CONSTRAINT tIMG_ibfk_1
        FOREIGN KEY (tID) 
        REFERENCES topics(id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# END OF TOPIC

# TOPIC QUOTE RELATIONSHIP

CREATE TABLE IF NOT EXISTS quotesTopicEN(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quoteID int(11) NOT NULL,
  topicID int(11) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_1
    FOREIGN KEY (topicID) 
    REFERENCES topics_en(topicID)
  ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT quote_ibfk_1 
    FOREIGN KEY (quoteID) REFERENCES quotes_en(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotesTopicES(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quoteID int(11) NOT NULL,
  topicID int(11) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_2
    FOREIGN KEY (topicID) 
    REFERENCES topics_es(topicID) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT quote_ibfk_2
    FOREIGN KEY (quoteID) REFERENCES quotes_es(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotesTopicPT(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quoteID int(11) NOT NULL,
  topicID int(11) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_3
    FOREIGN KEY (topicID)
    REFERENCES topics_pt(topicID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT quote_ibfk_3
    FOREIGN KEY (quoteID) REFERENCES quotes_pt(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS authors(
  authorID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  authorName varchar(255) NOT NULL UNIQUE,
  authorImage varchar(255) DEFAULT 'https://i.imgur.com/yatKEvy.jpg',
  sourceURL varchar(255) DEFAULT NULL,
  birth varchar(255) NOT NULL,
  died varchar(255) DEFAULT NULL,
  nationality varchar(255) NOT NULL,
  bio varchar(500) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS professions(
  professionID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  professionName varchar(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS authorProfession(
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  professionID int(11) NOT NULL,
  authorID int(11) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT profession_ibfk_1
    FOREIGN KEY (professionID)
    REFERENCES professions(professionID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT author_ibfk_1
    FOREIGN KEY (authorID) REFERENCES authors(authorID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



# CREATE THIS TABLES ON THE SERVER
CREATE TABLE IF NOT EXISTS users(
  userID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  oauth_provider varchar(255) DEFAULT NULL,
  oauth_uid varchar(255) DEFAULT NULL UNIQUE,
  fname varchar(255) NOT NULL,
  lname varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  username varchar(255) NOT NULL UNIQUE, # Which will be the email address with the @ part
  passwd varchar(45) NOT NULL,
  gender varchar(10) NOT NULL,
  picture varchar(255) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT now() ON UPDATE now()
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS pswd_digest(
  digestID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  digest varchar(255) NOT NULL,
  CONSTRAINT user_ibfk_1 
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS likes( # MODIFY FOR EVERY QUOTE LANGUAGE: EN, ES, PT
  likeID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  quoteID int(11) NOT NULL,
  CONSTRAINT user_ibfk_2
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT quote_ibfk_4
    FOREIGN KEY (quoteID) REFERENCES quotes(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS followers(
  followID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  followerID int(11) NOT NULL,
  CONSTRAINT user_ibfk_3
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT follower_ibfk_1 
    FOREIGN KEY (followerID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS userQuotes(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  quote TEXT NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS userQuotesTopic(
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    quoteID int(11) NOT NULL,
    topicID int(11) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT topic_ibfk_4
        FOREIGN KEY (topicID)
        REFERENCES topics(topicID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT userquote_ibfk_5
        FOREIGN KEY (quoteID) REFERENCES userQuotes(quoteID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS notifications(
  notificationID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  notification varchar(255) NOT NULL,
  seen TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_ibfk_4
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS mailing_list(
    mailID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    topicOption varchar(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


#DASHBOARD

    CREATE TABLE IF NOT EXISTS dashboard_usrs(
        id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        usrName varchar(50) NOT NULL UNIQUE,
        usrPswd varchar(50) NOT NULL,
        label varchar(15) NOT NULL,
        insrt TINYINT(1) NOT NULL DEFAULT 0,
        modif TINYINT(1) NOT NULL DEFAULT 0,
        del TINYINT(1) NOT NULL DEFAULT 0,
        lang varchar(25) NOT NULL DEFAULT 0,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;