CREATE DATABASE quotes;
USE quotes;

CREATE TABLE IF NOT EXISTS topics(
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(25) NOT NULL,
  topicImage varchar(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topics_es( # Topics: Spanish
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(25) NOT NULL,
  topicImage varchar(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS topics_pt( # Topics: Portuguese
  topicID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicName varchar(25) NOT NULL,
  topicImage varchar(50) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicID int(11) NOT NULL,
  quote varchar(255) NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_1 
    FOREIGN KEY (topicID) 
    REFERENCES topics(topicID) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes_es(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicID int(11) NOT NULL,
  quote varchar(255) NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_2
    FOREIGN KEY (topicID) 
    REFERENCES topics_es(topicID) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS quotes_es(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicID int(11) NOT NULL,
  quote varchar(255) NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_3
    FOREIGN KEY (topicID) 
    REFERENCES topics_pt(topicID) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS users(
  userID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  oauth_provider varchar(255) DEFAULT NULL,
  fname varchar(255) NOT NULL,
  lname varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  passwd varchar(40) NOT NULL,
  gender varchar(10) NOT NULL,
  picture varchar(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT now() ON UPDATE now()
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS likes(
  likeID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  quoteID int(11) NOT NULL,
  CONSTRAINT user_ibfk_1 
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT quote_ibfk_1 
    FOREIGN KEY (quoteID) REFERENCES quotes(quoteID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS followers(
  followID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  followerID int(11) NOT NULL,
  CONSTRAINT user_ibfk_2
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT follower_ibfk_1 
    FOREIGN KEY (followerID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS userQuotes(
  quoteID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  topicID int(11) NOT NULL,
  userID int(11) NOT NULL,
  quote varchar(255) NOT NULL,
  author varchar(255) NOT NULL DEFAULT 'Anonymous',
  quoteImage varchar(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT topic_ibfk_4
    FOREIGN KEY (topicID) 
    REFERENCES topics(topicID) 
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT user_ibfk_3
    FOREIGN KEY (userID) 
    REFERENCES users(userID) 
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS notifications(
  notificationID int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID int(11) NOT NULL,
  notification varchar(255) NOT NULL,
  seen TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_ibfk_4
    FOREIGN KEY (userID) REFERENCES users(userID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;